//! Authenticator-neutral Human Approval Authority domain contracts.
//!
//! The domain deliberately contains no Touch ID, fingerprint, WebAuthn or
//! hardware-specific types. Authenticators produce `ApprovalEvidence`; service
//! adapters verify that evidence without changing exact-action semantics.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use time::OffsetDateTime;
use uuid::Uuid;

pub const HAA_PROTOCOL_V1: &str = "dubbridge.haa.v1";

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum HaaError {
    #[error("invalid approval state transition from {from:?} to {to:?}")]
    InvalidStateTransition {
        from: ApprovalState,
        to: ApprovalState,
    },
}

/// Restricted, deterministic JSON-like value used by exact-action contracts.
///
/// Floating-point numbers are intentionally absent. Objects use `BTreeMap`, so
/// key ordering is deterministic before the service layer hashes serialized
/// content with the HAA domain-separated SHA-256 protocol.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CanonicalValue {
    Null,
    Bool(bool),
    Integer(i64),
    String(String),
    Array(Vec<CanonicalValue>),
    Object(BTreeMap<String, CanonicalValue>),
}

impl From<&str> for CanonicalValue {
    fn from(value: &str) -> Self {
        Self::String(value.to_owned())
    }
}

impl From<String> for CanonicalValue {
    fn from(value: String) -> Self {
        Self::String(value)
    }
}

impl From<i64> for CanonicalValue {
    fn from(value: i64) -> Self {
        Self::Integer(value)
    }
}

impl From<bool> for CanonicalValue {
    fn from(value: bool) -> Self {
        Self::Bool(value)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrincipalRef {
    pub kind: String,
    pub id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PolicyRef {
    pub id: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionPrecondition {
    pub name: String,
    pub expected: CanonicalValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionSpec {
    /// Versioned action schema, for example `git.merge.v1`.
    pub schema: String,
    pub action_type: String,
    pub resource: String,
    pub environment: Option<String>,
    pub parameters: BTreeMap<String, CanonicalValue>,
    pub preconditions: Vec<ActionPrecondition>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalIntent {
    pub action: ActionSpec,
    pub requester: PrincipalRef,
    pub audience: PrincipalRef,
    pub policy: PolicyRef,
    pub created_at: OffsetDateTime,
    pub expires_at: OffsetDateTime,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DisplayClaim {
    pub label: String,
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignatureEnvelope {
    pub algorithm: String,
    pub key_id: String,
    pub signature_b64: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalChallenge {
    pub protocol_version: String,
    pub request_id: Uuid,
    pub action_digest: String,
    pub intent_digest: String,
    /// Base64url/opaque CSPRNG output generated by the service layer.
    pub nonce: String,
    pub approver: PrincipalRef,
    pub audience: PrincipalRef,
    pub policy: PolicyRef,
    pub display_claims: Vec<DisplayClaim>,
    pub issued_at: OffsetDateTime,
    pub expires_at: OffsetDateTime,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalChallengePackage {
    pub challenge: ApprovalChallenge,
    pub haa_signature: SignatureEnvelope,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalEvidence {
    pub protocol_version: String,
    pub kind: String,
    pub authenticator_id: String,
    pub request_id: Uuid,
    pub challenge_digest: String,
    /// Authenticator-specific signed/assertion material. Never biometric data.
    pub payload: CanonicalValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VerifiedEvidence {
    pub request_id: Uuid,
    pub approver: PrincipalRef,
    pub authenticator_id: String,
    pub challenge_digest: String,
    pub verified_at: OffsetDateTime,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovalDecision {
    Approved,
    Rejected,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovalState {
    Requested,
    Pending,
    Approved,
    Rejected,
    Expired,
    Revoked,
    Consumed,
}

impl ApprovalState {
    #[must_use]
    pub fn can_transition_to(self, next: Self) -> bool {
        matches!(
            (self, next),
            (Self::Requested, Self::Pending)
                | (Self::Requested, Self::Rejected)
                | (Self::Requested, Self::Expired)
                | (Self::Pending, Self::Approved)
                | (Self::Pending, Self::Rejected)
                | (Self::Pending, Self::Expired)
                | (Self::Approved, Self::Consumed)
                | (Self::Approved, Self::Revoked)
                | (Self::Approved, Self::Expired)
        )
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalRequest {
    pub id: Uuid,
    pub intent: ApprovalIntent,
    pub action_digest: String,
    pub intent_digest: String,
    pub state: ApprovalState,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

impl ApprovalRequest {
    pub fn transition(&mut self, next: ApprovalState, at: OffsetDateTime) -> Result<(), HaaError> {
        if !self.state.can_transition_to(next) {
            return Err(HaaError::InvalidStateTransition {
                from: self.state,
                to: next,
            });
        }
        self.state = next;
        self.updated_at = at;
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ApprovalReceipt {
    pub protocol_version: String,
    pub receipt_id: Uuid,
    pub request_id: Uuid,
    pub action_digest: String,
    pub intent_digest: String,
    pub decision: ApprovalDecision,
    pub approver: PrincipalRef,
    pub authenticator_id: String,
    pub issued_at: OffsetDateTime,
    pub expires_at: OffsetDateTime,
    pub haa_signature: SignatureEnvelope,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExecutionGrant {
    pub protocol_version: String,
    pub grant_id: Uuid,
    pub request_id: Uuid,
    pub execution_id: Uuid,
    pub action_digest: String,
    pub audience: PrincipalRef,
    pub issued_at: OffsetDateTime,
    pub expires_at: OffsetDateTime,
    pub haa_signature: SignatureEnvelope,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthenticatorRecord {
    pub id: String,
    pub principal: PrincipalRef,
    pub kind: String,
    pub public_key: CanonicalValue,
    pub active: bool,
    pub enrolled_at: OffsetDateTime,
    pub revoked_at: Option<OffsetDateTime>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use time::macros::datetime;

    fn params(entries: &[(&str, CanonicalValue)]) -> BTreeMap<String, CanonicalValue> {
        entries
            .iter()
            .map(|(key, value)| ((*key).to_owned(), value.clone()))
            .collect()
    }

    #[test]
    fn action_parameters_have_deterministic_key_order() {
        let first = params(&[("region", "eu".into()), ("replicas", 2_i64.into())]);
        let second = params(&[("replicas", 2_i64.into()), ("region", "eu".into())]);
        assert_eq!(first, second);
        assert_eq!(
            first.keys().map(String::as_str).collect::<Vec<_>>(),
            vec!["region", "replicas"]
        );
    }

    #[test]
    fn lifecycle_allows_only_explicit_transitions() {
        assert!(ApprovalState::Pending.can_transition_to(ApprovalState::Approved));
        assert!(ApprovalState::Approved.can_transition_to(ApprovalState::Consumed));
        assert!(!ApprovalState::Consumed.can_transition_to(ApprovalState::Approved));
        assert!(!ApprovalState::Rejected.can_transition_to(ApprovalState::Pending));
    }

    #[test]
    fn transition_updates_state_and_timestamp() {
        let at = datetime!(2026-09-13 00:01 UTC);
        let intent = ApprovalIntent {
            action: ActionSpec {
                schema: "deployment.execute.v1".to_owned(),
                action_type: "deployment.execute".to_owned(),
                resource: "project/localdevengine".to_owned(),
                environment: Some("production".to_owned()),
                parameters: BTreeMap::new(),
                preconditions: Vec::new(),
            },
            requester: PrincipalRef {
                kind: "agent".to_owned(),
                id: "release-manager".to_owned(),
            },
            audience: PrincipalRef {
                kind: "executor".to_owned(),
                id: "deploy-service".to_owned(),
            },
            policy: PolicyRef {
                id: "prod-deploy".to_owned(),
                version: "1".to_owned(),
            },
            created_at: datetime!(2026-09-13 00:00 UTC),
            expires_at: datetime!(2026-09-13 00:05 UTC),
        };
        let mut request = ApprovalRequest {
            id: Uuid::nil(),
            intent,
            action_digest: "action".to_owned(),
            intent_digest: "intent".to_owned(),
            state: ApprovalState::Pending,
            created_at: datetime!(2026-09-13 00:00 UTC),
            updated_at: datetime!(2026-09-13 00:00 UTC),
        };
        request
            .transition(ApprovalState::Approved, at)
            .expect("valid transition");
        assert_eq!(request.state, ApprovalState::Approved);
        assert_eq!(request.updated_at, at);
    }

    #[test]
    fn invalid_transition_is_rejected() {
        let mut request = ApprovalRequest {
            id: Uuid::nil(),
            intent: ApprovalIntent {
                action: ActionSpec {
                    schema: "api.call.v1".to_owned(),
                    action_type: "api.call".to_owned(),
                    resource: "service/example".to_owned(),
                    environment: None,
                    parameters: BTreeMap::new(),
                    preconditions: Vec::new(),
                },
                requester: PrincipalRef {
                    kind: "agent".to_owned(),
                    id: "agent-1".to_owned(),
                },
                audience: PrincipalRef {
                    kind: "executor".to_owned(),
                    id: "executor-1".to_owned(),
                },
                policy: PolicyRef {
                    id: "default".to_owned(),
                    version: "1".to_owned(),
                },
                created_at: datetime!(2026-09-13 00:00 UTC),
                expires_at: datetime!(2026-09-13 00:05 UTC),
            },
            action_digest: "action".to_owned(),
            intent_digest: "intent".to_owned(),
            state: ApprovalState::Consumed,
            created_at: datetime!(2026-09-13 00:00 UTC),
            updated_at: datetime!(2026-09-13 00:00 UTC),
        };
        let error = request
            .transition(ApprovalState::Approved, datetime!(2026-09-13 00:01 UTC))
            .expect_err("consumed approval must not reopen");
        assert!(matches!(error, HaaError::InvalidStateTransition { .. }));
    }
}
