[package]
name = "dubbridge-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
apalis.workspace = true
apalis-redis.workspace = true
async-trait.workspace = true
dubbridge-connectors = { path = "../connectors" }
dubbridge-db = { path = "../db" }
dubbridge-domain = { path = "../domain" }
dubbridge-p2p = { path = "../p2p" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror = "2.0"
time = { workspace = true, features = ["parsing"] }
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio-test.workspace = true

[lints]
workspace = true
