#!/usr/bin/env python3
"""Diff-based maintainability guard for backend and mobile code."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "code generated",
    "do not edit",
    "generated by",
)


@dataclass(frozen=True)
class Profile:
    name: str
    added_line_budget: int
    added_block_budget: int
    repeated_line_budget: int
    duplicate_window: int


@dataclass(frozen=True)
class AddedLine:
    path: str
    text: str
    hunk: int
    line_no: int


@dataclass(frozen=True)
class Violation:
    path: str
    message: str


RUST_SOURCE = Profile("backend Rust source", 300, 140, 10, 6)
RUST_TEST = Profile("backend Rust test", 500, 220, 14, 8)
MOBILE_SOURCE = Profile("mobile source", 220, 110, 10, 6)
MOBILE_TEST = Profile("mobile test", 450, 220, 14, 8)


def run_git(args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout


def discover_base(explicit_base: str | None) -> str | None:
    candidates = [
        explicit_base,
        os.environ.get("DUBBRIDGE_MAINTAINABILITY_BASE"),
        "origin/main",
        "HEAD",
    ]
    for candidate in candidates:
        if not candidate:
            continue
        result = subprocess.run(
            ["git", "rev-parse", "--verify", candidate],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if result.returncode == 0:
            return candidate
    return None


def changed_files(base: str | None) -> list[str]:
    if base is None:
        output = run_git(["diff", "--name-only"])
    else:
        output = run_git(["diff", "--name-only", base, "--"])
    return sorted({line.strip() for line in output.splitlines() if line.strip()})


def classify_path(path: str) -> Profile | None:
    if re.match(r"^(apps|crates)/.*\.rs$", path):
        if "/tests/" in path or path.endswith("_test.rs"):
            return RUST_TEST
        return RUST_SOURCE
    if re.match(r"^mobile/(src|__tests__)/.*\.(ts|tsx)$", path):
        if path.startswith("mobile/__tests__/") or path.endswith(".test.ts") or path.endswith(".test.tsx"):
            return MOBILE_TEST
        return MOBILE_SOURCE
    return None


def parse_added_lines(diff_text: str) -> list[AddedLine]:
    current_path: str | None = None
    current_hunk = 0
    added_line_no = 0
    records: list[AddedLine] = []

    for raw_line in diff_text.splitlines():
        if raw_line.startswith("diff --git "):
            current_path = None
            current_hunk = 0
            added_line_no = 0
            continue
        if raw_line.startswith("+++ b/"):
            current_path = raw_line.removeprefix("+++ b/")
            continue
        if raw_line.startswith("@@ "):
            current_hunk += 1
            match = re.search(r"\+(\d+)", raw_line)
            added_line_no = int(match.group(1)) if match else 0
            continue
        if raw_line.startswith("+") and not raw_line.startswith("+++"):
            if current_path is not None and classify_path(current_path) is not None:
                records.append(
                    AddedLine(
                        path=current_path,
                        text=raw_line[1:],
                        hunk=current_hunk,
                        line_no=added_line_no,
                    )
                )
            added_line_no += 1

    return records


def added_lines_for(base: str | None, files: list[str]) -> list[AddedLine]:
    code_files = [path for path in files if classify_path(path) is not None and Path(path).exists()]
    if not code_files:
        return []
    args = ["diff", "--unified=0", "--no-color"]
    if base is not None:
        args.append(base)
    args.extend(["--", *code_files])
    return parse_added_lines(run_git(args))


def is_meaningful_line(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return False
    if stripped in {"{", "}", "},", ");", "];", "};"}:
        return False
    if stripped.startswith(("//", "/*", "*")):
        return False
    return True


def normalize_line(text: str) -> str:
    stripped = text.strip()
    stripped = re.sub(r"\s+", " ", stripped)
    return stripped.rstrip(",;")


def group_by_path(lines: Iterable[AddedLine]) -> dict[str, list[AddedLine]]:
    grouped: dict[str, list[AddedLine]] = {}
    for line in lines:
        grouped.setdefault(line.path, []).append(line)
    return grouped


def check_added_line_budgets(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        meaningful_count = sum(1 for line in lines if is_meaningful_line(line.text))
        if meaningful_count > profile.added_line_budget:
            violations.append(
                Violation(
                    path,
                    f"{meaningful_count} meaningful added lines exceed {profile.name} budget "
                    f"of {profile.added_line_budget}",
                )
            )
    return violations


def check_added_blocks(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        block_counts: Counter[int] = Counter()
        for line in lines:
            if is_meaningful_line(line.text):
                block_counts[line.hunk] += 1
        for hunk, count in sorted(block_counts.items()):
            if count > profile.added_block_budget:
                violations.append(
                    Violation(
                        path,
                        f"hunk {hunk} adds {count} uninterrupted meaningful lines; "
                        f"budget is {profile.added_block_budget}",
                    )
                )
    return violations


def check_generated_markers(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        for line in lines:
            lower = line.text.lower()
            marker = next((item for item in GENERATED_MARKERS if item in lower), None)
            if marker is not None:
                violations.append(
                    Violation(path, f"generated-source marker '{marker}' added at line {line.line_no}")
                )
                break
    return violations


def check_repeated_lines(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        normalized = [
            normalize_line(line.text)
            for line in lines
            if is_meaningful_line(line.text) and len(normalize_line(line.text)) >= 12
        ]
        counts = Counter(normalized)
        repeated = [(line, count) for line, count in counts.items() if count > profile.repeated_line_budget]
        if repeated:
            sample, count = sorted(repeated, key=lambda item: item[1], reverse=True)[0]
            violations.append(
                Violation(
                    path,
                    f"line repeated {count} times in added code; budget is "
                    f"{profile.repeated_line_budget}: {sample[:90]}",
                )
            )
    return violations


def check_duplicate_blocks(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    seen: dict[tuple[str, ...], tuple[str, int]] = {}
    violations: list[Violation] = []

    for path, lines in sorted(grouped.items()):
        profile = classify_path(path)
        if profile is None:
            continue
        normalized = [
            normalize_line(line.text)
            for line in lines
            if is_meaningful_line(line.text) and len(normalize_line(line.text)) >= 8
        ]
        if len(normalized) < profile.duplicate_window:
            continue

        for index in range(0, len(normalized) - profile.duplicate_window + 1):
            window = tuple(normalized[index : index + profile.duplicate_window])
            if len("\n".join(window)) < 160:
                continue
            previous = seen.get(window)
            if previous is not None and previous[0] != path:
                violations.append(
                    Violation(
                        path,
                        f"duplicates a {profile.duplicate_window}-line added block from "
                        f"{previous[0]} near added block {previous[1]}",
                    )
                )
                return violations
            seen.setdefault(window, (path, index + 1))

    return violations


def analyze_added_lines(added_lines: list[AddedLine]) -> list[Violation]:
    grouped = group_by_path(added_lines)
    violations: list[Violation] = []
    violations.extend(check_added_line_budgets(grouped))
    violations.extend(check_added_blocks(grouped))
    violations.extend(check_generated_markers(grouped))
    violations.extend(check_repeated_lines(grouped))
    violations.extend(check_duplicate_blocks(grouped))
    return violations


def render_report(violations: list[Violation]) -> str:
    if not violations:
        return "Maintainability gate passed."
    lines = ["Maintainability gate failed:"]
    for violation in violations:
        lines.append(f"- {violation.path}: {violation.message}")
    lines.append("")
    lines.append("Split the change, remove generated bulk, or simplify duplicated code before pushing.")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", help="git revision to diff against")
    parser.add_argument("--files", nargs="*", help="explicit files to inspect")
    args = parser.parse_args(argv)

    base = discover_base(args.base)
    files = args.files if args.files is not None else changed_files(base)
    added_lines = added_lines_for(base, files)
    violations = analyze_added_lines(added_lines)
    print(render_report(violations))
    return 1 if violations else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
