#!/usr/bin/env python3

from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path


SCRIPT = Path(__file__).with_name("check-maintainability.py")
SPEC = importlib.util.spec_from_file_location("check_maintainability", SCRIPT)
assert SPEC is not None
checker = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules["check_maintainability"] = checker
SPEC.loader.exec_module(checker)


def added(path: str, lines: list[str]) -> list[object]:
    return [checker.AddedLine(path=path, text=line, hunk=1, line_no=index + 1) for index, line in enumerate(lines)]


class MaintainabilityGateTest(unittest.TestCase):
    def test_hp1_small_backend_rust_diff_passes(self) -> None:
        lines = added(
            "crates/domain/src/example.rs",
            [
                "pub fn display_name(value: &str) -> String {",
                '    format!("asset:{value}")',
                "}",
            ],
        )

        self.assertEqual(checker.analyze_added_lines(lines), [])

    def test_hp2_small_mobile_source_diff_passes(self) -> None:
        lines = added(
            "mobile/src/screens/ExampleScreen.tsx",
            [
                "export function ExampleScreen() {",
                '  return <Text testID="example">Ready</Text>;',
                "}",
            ],
        )

        self.assertEqual(checker.analyze_added_lines(lines), [])

    def test_ec1_mobile_source_added_line_budget_fails(self) -> None:
        lines = added(
            "mobile/src/screens/HugeGeneratedScreen.tsx",
            [f"const generatedValue{i} = {i};" for i in range(checker.MOBILE_SOURCE.added_line_budget + 1)],
        )

        violations = checker.analyze_added_lines(lines)

        self.assertTrue(any("exceed mobile source budget" in item.message for item in violations))
        self.assertTrue(any(item.path == "mobile/src/screens/HugeGeneratedScreen.tsx" for item in violations))

    def test_ec2_backend_generated_marker_fails(self) -> None:
        lines = added(
            "crates/domain/src/generatedish.rs",
            [
                "// Code generated by a model. DO NOT EDIT.",
                "pub fn generated_value() -> &'static str {",
                '    "x"',
                "}",
            ],
        )

        violations = checker.analyze_added_lines(lines)

        self.assertTrue(any("generated-source marker" in item.message for item in violations))

    def test_ec3_repeated_added_lines_fail(self) -> None:
        repeated_line = "const repeatedGeneratedField = buildGeneratedField();"
        lines = added(
            "mobile/src/screens/RepeatedScreen.tsx",
            [repeated_line for _ in range(checker.MOBILE_SOURCE.repeated_line_budget + 1)],
        )

        violations = checker.analyze_added_lines(lines)

        self.assertTrue(any("line repeated" in item.message for item in violations))

    def test_ec4_duplicate_added_blocks_across_files_fail(self) -> None:
        block = [
            "const alphaGeneratedField = normalizeGeneratedField(alphaInput);",
            "const betaGeneratedField = normalizeGeneratedField(betaInput);",
            "const gammaGeneratedField = normalizeGeneratedField(gammaInput);",
            "const deltaGeneratedField = normalizeGeneratedField(deltaInput);",
            "const epsilonGeneratedField = normalizeGeneratedField(epsilonInput);",
            "const zetaGeneratedField = normalizeGeneratedField(zetaInput);",
        ]
        lines = added("mobile/src/screens/FirstScreen.tsx", block)
        lines += added("mobile/src/screens/SecondScreen.tsx", block)

        violations = checker.analyze_added_lines(lines)

        self.assertTrue(any("duplicates a 6-line added block" in item.message for item in violations))

    def test_parse_added_lines_only_keeps_supported_code_paths(self) -> None:
        diff = """diff --git a/README.md b/README.md
+++ b/README.md
@@ -0,0 +1 @@
+docs only
diff --git a/mobile/src/screens/Example.tsx b/mobile/src/screens/Example.tsx
+++ b/mobile/src/screens/Example.tsx
@@ -0,0 +10,2 @@
+export const value = 1;
+export const label = "ready";
"""

        lines = checker.parse_added_lines(diff)

        self.assertEqual([line.path for line in lines], ["mobile/src/screens/Example.tsx", "mobile/src/screens/Example.tsx"])
        self.assertEqual(lines[0].line_no, 10)


if __name__ == "__main__":
    unittest.main()
