#!/usr/bin/env python3
"""Diff-based maintainability guard for backend and mobile code."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "code generated",
    "do not edit",
    "generated by",
)


@dataclass(frozen=True)
class Profile:
    name: str
    added_block_budget: int
    repeated_line_budget: int
    duplicate_window: int
    declaration_budget: int
    duplicate_min_chars: int
    generic_name_budget: int
    long_line_budget: int


@dataclass(frozen=True)
class AddedLine:
    path: str
    text: str
    hunk: int
    line_no: int


@dataclass(frozen=True)
class Violation:
    path: str
    message: str


RUST_SOURCE = Profile("backend Rust source", 65, 8, 4, 40, 90, 10, 15)
RUST_TEST = Profile("backend Rust test", 120, 10, 5, 60, 120, 18, 20)
MOBILE_SOURCE = Profile("mobile source", 45, 4, 3, 20, 70, 8, 8)
MOBILE_TEST = Profile("mobile test", 120, 6, 5, 40, 110, 14, 12)

GENERIC_NAME_RE = re.compile(
    r"\b("
    r"generated[a-zA-Z0-9_]*|"
    r"temp[a-zA-Z0-9_]*|"
    r"placeholder[a-zA-Z0-9_]*|"
    r"foo|bar|baz|qux|"
    r"value\d+|item\d+|field\d+|data\d+|result\d+|thing\d+"
    r")\b"
)

# Panic-on-error calls that are grandfathered in existing source but must not be
# *added* to production Rust. Macro-based risks (panic!/todo!/dbg!/print*) are
# enforced workspace-wide by clippy ([workspace.lints.clippy]); unwrap/expect
# have hundreds of historical call sites, so they cannot be denied globally and
# are ratcheted here on the diff instead. Tests keep their freedom to unwrap.
RUNTIME_RISK_RE = re.compile(r"\.unwrap\(\)|\.expect\(")


def _find_cfg_test_line(path: str) -> int | None:
    """Return the 1-indexed line number of the first #[cfg(test)] in a Rust file."""
    try:
        with open(path, encoding="utf-8") as f:
            for i, line in enumerate(f, 1):
                if line.strip() == "#[cfg(test)]":
                    return i
    except OSError:
        pass
    return None


def run_git(args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout


def discover_base(explicit_base: str | None) -> str | None:
    candidates = [
        explicit_base,
        os.environ.get("DUBBRIDGE_MAINTAINABILITY_BASE"),
        "origin/main",
        "HEAD",
    ]
    for candidate in candidates:
        if not candidate:
            continue
        result = subprocess.run(
            ["git", "cat-file", "-e", f"{candidate}^{{commit}}"],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if result.returncode == 0:
            return candidate
    return None


def changed_files(base: str | None) -> list[str]:
    if base is None:
        output = run_git(["diff", "--name-only"])
    else:
        output = run_git(["diff", "--name-only", base, "--"])
    return sorted({line.strip() for line in output.splitlines() if line.strip()})


def classify_path(path: str) -> Profile | None:
    if re.match(r"^(apps|crates)/.*\.rs$", path):
        if "/tests/" in path or path.endswith("_test.rs"):
            return RUST_TEST
        return RUST_SOURCE
    if re.match(r"^mobile/(src|__tests__)/.*\.(ts|tsx)$", path):
        if path.startswith("mobile/__tests__/") or path.endswith(".test.ts") or path.endswith(".test.tsx"):
            return MOBILE_TEST
        return MOBILE_SOURCE
    return None


def parse_added_lines(diff_text: str) -> list[AddedLine]:
    current_path: str | None = None
    current_hunk = 0
    added_line_no = 0
    records: list[AddedLine] = []

    for raw_line in diff_text.splitlines():
        if raw_line.startswith("diff --git "):
            current_path = None
            current_hunk = 0
            added_line_no = 0
            continue
        if raw_line.startswith("+++ b/"):
            current_path = raw_line.removeprefix("+++ b/")
            continue
        if raw_line.startswith("@@ "):
            current_hunk += 1
            match = re.search(r"\+(\d+)", raw_line)
            added_line_no = int(match.group(1)) if match else 0
            continue
        if raw_line.startswith("+") and not raw_line.startswith("+++"):
            if current_path is not None and classify_path(current_path) is not None:
                records.append(
                    AddedLine(
                        path=current_path,
                        text=raw_line[1:],
                        hunk=current_hunk,
                        line_no=added_line_no,
                    )
                )
            added_line_no += 1

    return records


def added_lines_for(base: str | None, files: list[str]) -> list[AddedLine]:
    code_files = [path for path in files if classify_path(path) is not None and Path(path).exists()]
    if not code_files:
        return []
    args = ["diff", "--unified=0", "--no-color"]
    if base is not None:
        args.append(base)
    args.extend(["--", *code_files])
    return parse_added_lines(run_git(args))


def is_meaningful_line(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return False
    if stripped in {"{", "}", "},", ");", "];", "};"}:
        return False
    if stripped.startswith(("//", "/*", "*")):
        return False
    return True


def normalize_line(text: str) -> str:
    stripped = text.strip()
    stripped = re.sub(r"\s+", " ", stripped)
    return stripped.rstrip(",;")


def is_declaration_line(path: str, text: str) -> bool:
    normalized = normalize_line(text)
    if classify_path(path) in {RUST_SOURCE, RUST_TEST}:
        return bool(
            re.match(
                r"^(pub )?(async )?fn\b|^impl\b|^(pub )?(struct|enum|trait|mod)\b|^type\b|^use\b",
                normalized,
            )
        )
    return bool(
        re.match(
            r"^(export )?(async )?function\b|^(export )?const\b|^(export )?(type|interface|class)\b|^import\b",
            normalized,
        )
    )


def group_by_path(lines: Iterable[AddedLine]) -> dict[str, list[AddedLine]]:
    grouped: dict[str, list[AddedLine]] = {}
    for line in lines:
        grouped.setdefault(line.path, []).append(line)
    return grouped


def _longest_meaningful_run(hunk_lines: list[AddedLine]) -> int:
    """Return the length of the longest contiguous run of meaningful lines."""
    max_run = current_run = 0
    for line in hunk_lines:
        if is_meaningful_line(line.text):
            current_run += 1
            if current_run > max_run:
                max_run = current_run
        else:
            current_run = 0
    return max_run


def check_added_blocks(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        # For RUST_SOURCE files that contain a #[cfg(test)] module, lines past
        # that module boundary use the RUST_TEST budget.
        test_start = _find_cfg_test_line(path) if profile is RUST_SOURCE else None

        hunk_buckets: dict[tuple[int, bool], list[AddedLine]] = {}
        for line in lines:
            is_test = test_start is not None and line.line_no >= test_start
            hunk_buckets.setdefault((line.hunk, is_test), []).append(line)

        for (hunk, is_test), hunk_lines in sorted(hunk_buckets.items()):
            budget_profile = RUST_TEST if is_test else profile
            longest = _longest_meaningful_run(hunk_lines)
            if longest > budget_profile.added_block_budget:
                label = "test module, " if is_test else ""
                violations.append(
                    Violation(
                        path,
                        f"hunk {hunk} ({label}longest contiguous run {longest} meaningful lines; "
                        f"budget is {budget_profile.added_block_budget})",
                    )
                )
    return violations


def check_generated_markers(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        for line in lines:
            lower = line.text.lower()
            marker = next((item for item in GENERATED_MARKERS if item in lower), None)
            if marker is not None:
                violations.append(
                    Violation(path, f"generated-source marker '{marker}' added at line {line.line_no}")
                )
                break
    return violations


def check_repeated_lines(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        normalized = [
            normalize_line(line.text)
            for line in lines
            if is_meaningful_line(line.text) and len(normalize_line(line.text)) >= 12
        ]
        counts = Counter(normalized)
        repeated = [(line, count) for line, count in counts.items() if count > profile.repeated_line_budget]
        if repeated:
            sample, count = sorted(repeated, key=lambda item: item[1], reverse=True)[0]
            violations.append(
                Violation(
                    path,
                    f"line repeated {count} times in added code; budget is "
                    f"{profile.repeated_line_budget}: {sample[:90]}",
                )
            )
    return violations


def check_declaration_bursts(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        # Exclude declarations that fall inside a #[cfg(test)] module.
        test_start = _find_cfg_test_line(path) if profile is RUST_SOURCE else None
        declaration_count = sum(
            1
            for line in lines
            if is_meaningful_line(line.text)
            and is_declaration_line(path, line.text)
            and (test_start is None or line.line_no < test_start)
        )
        if declaration_count > profile.declaration_budget:
            violations.append(
                Violation(
                    path,
                    f"{declaration_count} declaration/import lines exceed {profile.name} declaration budget "
                    f"of {profile.declaration_budget}",
                )
            )
    return violations


def check_generic_name_bursts(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        count = sum(
            1
            for line in lines
            if is_meaningful_line(line.text) and GENERIC_NAME_RE.search(normalize_line(line.text))
        )
        if count > profile.generic_name_budget:
            violations.append(
                Violation(
                    path,
                    f"{count} generic generated-style identifiers exceed {profile.name} generic-name budget "
                    f"of {profile.generic_name_budget}",
                )
            )
    return violations


def check_long_line_bursts(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    violations: list[Violation] = []
    for path, lines in grouped.items():
        profile = classify_path(path)
        if profile is None:
            continue
        count = sum(1 for line in lines if is_meaningful_line(line.text) and len(line.text.rstrip()) >= 100)
        if count > profile.long_line_budget:
            violations.append(
                Violation(
                    path,
                    f"{count} added lines are 100+ chars, exceeding {profile.name} long-line budget "
                    f"of {profile.long_line_budget}",
                )
            )
    return violations


def check_duplicate_blocks(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    seen: dict[tuple[str, ...], tuple[str, int]] = {}
    violations: list[Violation] = []

    for path, lines in sorted(grouped.items()):
        profile = classify_path(path)
        if profile is None:
            continue
        normalized = [
            normalize_line(line.text)
            for line in lines
            if is_meaningful_line(line.text) and len(normalize_line(line.text)) >= 8
        ]
        if len(normalized) < profile.duplicate_window:
            continue

        for index in range(0, len(normalized) - profile.duplicate_window + 1):
            window = tuple(normalized[index : index + profile.duplicate_window])
            if len("\n".join(window)) < profile.duplicate_min_chars:
                continue
            previous = seen.get(window)
            if previous is not None and previous[0] != path:
                violations.append(
                    Violation(
                        path,
                        f"duplicates a {profile.duplicate_window}-line added block from "
                        f"{previous[0]} near added block {previous[1]}",
                    )
                )
                return violations
            seen.setdefault(window, (path, index + 1))

    return violations


def check_runtime_risk_additions(grouped: dict[str, list[AddedLine]]) -> list[Violation]:
    """Block newly-added unwrap()/expect() in production Rust source.

    Existing call sites are grandfathered because the gate only inspects added
    diff lines, not the historical baseline. Lines inside a #[cfg(test)] module
    are exempt even when the file is otherwise classified as RUST_SOURCE.
    """
    violations: list[Violation] = []
    for path, lines in grouped.items():
        if classify_path(path) is not RUST_SOURCE:
            continue
        test_start = _find_cfg_test_line(path)
        for line in lines:
            if test_start is not None and line.line_no >= test_start:
                continue
            if not is_meaningful_line(line.text):
                continue
            match = RUNTIME_RISK_RE.search(line.text)
            if match is None:
                continue
            call = "unwrap()" if match.group(0).startswith(".unwrap") else "expect()"
            violations.append(
                Violation(
                    path,
                    f"adds .{call} at line {line.line_no}; return Result/Option and "
                    f"propagate with `?` instead of panicking in production source",
                )
            )
    return violations


def analyze_added_lines(added_lines: list[AddedLine]) -> list[Violation]:
    grouped = group_by_path(added_lines)
    violations: list[Violation] = []
    violations.extend(check_added_blocks(grouped))
    violations.extend(check_generated_markers(grouped))
    violations.extend(check_repeated_lines(grouped))
    violations.extend(check_declaration_bursts(grouped))
    violations.extend(check_generic_name_bursts(grouped))
    violations.extend(check_long_line_bursts(grouped))
    violations.extend(check_duplicate_blocks(grouped))
    violations.extend(check_runtime_risk_additions(grouped))
    return violations


def render_report(violations: list[Violation]) -> str:
    if not violations:
        return "Maintainability gate passed."
    lines = ["Maintainability gate failed:"]
    for violation in violations:
        lines.append(f"- {violation.path}: {violation.message}")
    lines.append("")
    lines.append("Split the change, remove generated bulk, or simplify duplicated code before pushing.")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", help="git revision to diff against")
    parser.add_argument("--files", nargs="*", help="explicit files to inspect")
    args = parser.parse_args(argv)

    base = discover_base(args.base)
    files = args.files if args.files is not None else changed_files(base)
    added_lines = added_lines_for(base, files)
    violations = analyze_added_lines(added_lines)
    print(render_report(violations))
    return 1 if violations else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
