#!/usr/bin/env python3
"""Thin local runtime adapter for Ollama's /v1/systemone endpoint.

The implementation uses only Python's standard library and is fully unit-testable
without Ollama. Actual endpoint execution is intentionally a separate local step.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import time
import urllib.error
import urllib.request
from typing import Any, Callable

DEFAULT_ENDPOINT = "http://localhost:11434/v1/systemone"
DEFAULT_TIMEOUT_SECONDS = 120


def request_sha256(request_payload: dict[str, Any]) -> str:
    payload = json.dumps(
        request_payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def invoke_systemone(
    request_payload: dict[str, Any],
    *,
    endpoint: str = DEFAULT_ENDPOINT,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
    opener: Callable[..., Any] = urllib.request.urlopen,
) -> dict[str, Any]:
    encoded = json.dumps(request_payload).encode("utf-8")
    req = urllib.request.Request(
        endpoint,
        data=encoded,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    started = time.perf_counter()
    try:
        with opener(req, timeout=timeout) as response:
            raw = response.read()
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise RuntimeError(f"systemone invocation failed: {exc}") from exc
    latency_ms = round((time.perf_counter() - started) * 1000.0, 3)
    try:
        data = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RuntimeError("systemone endpoint returned invalid JSON") from exc
    if not isinstance(data, dict):
        raise RuntimeError("systemone endpoint returned non-object JSON")
    return {
        "request_sha256": request_sha256(request_payload),
        "latency_ms": latency_ms,
        "response": data,
    }


def _read_json(path: str) -> dict[str, Any]:
    with open(path, encoding="utf-8") as stream:
        data = json.load(stream)
    if not isinstance(data, dict):
        raise ValueError("request must be a JSON object")
    return data


def _write_json(data: dict[str, Any], path: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as stream:
        json.dump(data, stream, indent=2, sort_keys=True)
        stream.write("\n")
    os.replace(tmp, path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Invoke a local System One endpoint")
    parser.add_argument("request", help="Request JSON generated by review_decision.py packet")
    parser.add_argument("--endpoint", default=os.environ.get("DUBBRIDGE_SYSTEMONE_ENDPOINT", DEFAULT_ENDPOINT))
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT_SECONDS)
    parser.add_argument("--output", required=True, help="Raw response envelope path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = invoke_systemone(
        _read_json(args.request),
        endpoint=args.endpoint,
        timeout=args.timeout,
    )
    _write_json(result, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
